// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5zqf974CFBJuGTe4TEBqYjIFhEfi93-M',
    appId: '1:931773443632:android:63d60d59c7038fb17247f5',
    messagingSenderId: '931773443632',
    projectId: 'recipe-app-61369',
    storageBucket: 'recipe-app-61369.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9S4QeveE0LOgRLM3A32KOAFrOOeDYsMA',
    appId: '1:931773443632:ios:c157dee3c992cab37247f5',
    messagingSenderId: '931773443632',
    projectId: 'recipe-app-61369',
    storageBucket: 'recipe-app-61369.appspot.com',
    iosBundleId: 'com.example.recipeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9S4QeveE0LOgRLM3A32KOAFrOOeDYsMA',
    appId: '1:931773443632:ios:3536ab6702a231987247f5',
    messagingSenderId: '931773443632',
    projectId: 'recipe-app-61369',
    storageBucket: 'recipe-app-61369.appspot.com',
    iosBundleId: 'com.example.recipeApplication.RunnerTests',
  );
}
